ITSERVICES:
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - ELASTICSEARCH:
      image: elasticsearch:2.0.2
      sleep: 10
      env:
        - ES_JAVA_OPTS="-Des.cluster.name=%%JUID -Des.network.host=%%OWNHOSTNAME"
  - CASSANDRA:
      image: stratio/cassandra:2.2.5
      sleep: 10
      env:
        - MAX_HEAP=256M

ITPARAMETERS: >
    -DMONGO_HOST=%%MONGODB
    -DCASSANDRA_HOST=%%CASSANDRA#0
    -DELASTICSEARCH.hosts.0=%%OWNHOSTNAME
    -DELASTICSEARCH.cluster=%%JUID
