ITSERVICES:
  - ZOOKEEPER:
      image: confluent/zookeeper:3.4.6-cp1
      env:
        - zk_id=1
      sleep: 10
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - ELASTICSEARCH:
      image: elasticsearch:2.0.2
      sleep: 10
      env:
        - ES_JAVA_OPTS="-Des.cluster.name=%%JUID -Des.network.host=%%OWNHOSTNAME"
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:3.0.7.3
      volumes:
        - jts:1.14.0
#        - stratio/cassandra-airlines:2.2.5
      sleep: 10
      env:
        - MAX_HEAP=256M
  - KAFKA:
      image: confluent/kafka:0.10.0.0-cp1
      env:
        - KAFKA_ZOOKEEPER_CONNECT=%%ZOOKEEPER:2181
        - KAFKA_ADVERTISED_HOST_NAME=%%OWNHOSTNAME
  - UBUNTU:
      image: stratio/ubuntu-base:16.04
      ssh: true

ITPARAMETERS: >
    -DMONGO_HOST=%%MONGODB
    -DCASSANDRA_HOST=%%CASSANDRA#0
    -DES_NODE=%%ELASTICSEARCH#0
    -DES_CLUSTER=%%JUID
    -DZOOKEEPER_HOSTS=%%ZOOKEEPER:2181
    -DKAFKA_HOSTS=%%KAFKA:9092
    -DSSH=%%UBUNTU
    -DSLEEPTEST=1
