ITSERVICES:
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - ELASTICSEARCH:
      image: stratio/elasticsearch:2.0.2
      sleep: 5
  - CASSANDRA:
      image: stratio/cassandra:2.2.5
      sleep: 10
      env:
        - MAX_HEAP=256M

ITPARAMETERS: >
    -DMONGO_HOST=%%MONGODB
    -DES_NODE=%%ELASTICSEARCH#0
    -DES_CLUSTER=elasticsearch
    -DCASSANDRA_HOST=%%CASSANDRA#0
